name: student-management ci-cd
on:
  push:
    branches:
      - master
jobs:
  ci-cd:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v7

     
      
